import { useState } from 'react';
import { FileLock2, Loader2, ShieldCheck, Copy } from 'lucide-react';
import { Modal } from '@/lib/ui/Modal';
import { useGenerateEvidenceBundle, useReportJob, useReportData } from './api';
import { useStepUpStore } from '@/lib/state/stepUpStore';
import { auditQueue } from '@/lib/audit/auditQueue';
import { toast } from '@/lib/state/toastStore';
import { formatLocalWithZone } from '@/lib/utils/time';
import { useHasPermission } from '@/features/auth/RoleGate';

interface EvidenceManifest {
  reportId: string;
  generatedBy: string;
  generatedAt: string;
  cameraId: string;
  cameraName: string;
  annotatedSnapshotUrl: string;
  sha256: string;
  systemGenerated: boolean;
}

interface Props {
  cameraId: string;
  at: string;
  alertId?: string;
}

export function EvidenceBundleButton({ cameraId, at, alertId }: Props): React.JSX.Element | null {
  const canExport = useHasPermission('exportEvidenceBundle');
  const [open, setOpen] = useState(false);
  const [jobId, setJobId] = useState<string | null>(null);
  const generate = useGenerateEvidenceBundle();
  const requestStepUp = useStepUpStore((s) => s.request);
  const { data: job } = useReportJob(jobId);
  const { data: manifest } = useReportData<EvidenceManifest>(job);

  if (!canExport) return null;

  async function handleStart(): Promise<void> {
    setOpen(true);
    const ok = await requestStepUp('export an evidence bundle');
    if (!ok) {
      setOpen(false);
      return;
    }
    const result = await generate.mutateAsync({ cameraId, at, alertId });
    setJobId(result.id);
    auditQueue.enqueue('report.evidence_bundle', cameraId, { alertId, at, reportId: result.reportId });
  }

  function copyChecksum(): void {
    if (manifest) void navigator.clipboard.writeText(manifest.sha256);
    toast({ severity: 'info', title: 'Checksum copied', autoDismissMs: 3000 });
  }

  return (
    <>
      <button
        type="button"
        onClick={() => void handleStart()}
        className="flex items-center gap-1.5 rounded-md border border-border px-2.5 py-1 text-xs text-fg-secondary hover:bg-bg-raised"
      >
        <FileLock2 className="h-3.5 w-3.5" aria-hidden="true" />
        Export evidence bundle
      </button>
      {open && (
        <Modal title="Evidence bundle" onClose={() => setOpen(false)}>
          {!job || job.status === 'QUEUED' || job.status === 'RUNNING' ? (
            <div className="flex items-center gap-2 py-6 text-sm text-fg-secondary">
              <Loader2 className="h-4 w-4 animate-spin" aria-hidden="true" />
              Generating chain-of-custody bundle… {job?.progressPct ?? 0}%
            </div>
          ) : job.status === 'FAILED' ? (
            <p className="text-sm text-severity-critical">{job.error}</p>
          ) : manifest ? (
            <div className="space-y-3">
              <div className="flex items-center gap-2 text-status-online">
                <ShieldCheck className="h-5 w-5" aria-hidden="true" />
                <span className="text-sm font-medium">Bundle generated — system-generated evidence</span>
              </div>
              <img src={manifest.annotatedSnapshotUrl} alt="Annotated evidence snapshot" className="w-full rounded-md border border-border" />
              <dl className="space-y-1 text-xs text-fg-secondary">
                <div className="flex justify-between">
                  <dt>Report ID</dt>
                  <dd className="font-mono text-fg-primary">{manifest.reportId}</dd>
                </div>
                <div className="flex justify-between">
                  <dt>Generated by</dt>
                  <dd>{manifest.generatedBy}</dd>
                </div>
                <div className="flex justify-between">
                  <dt>Generated at</dt>
                  <dd>{formatLocalWithZone(manifest.generatedAt)}</dd>
                </div>
              </dl>
              <div className="flex items-center gap-2 rounded-md border border-border bg-bg-raised p-2">
                <span className="flex-1 truncate font-mono text-[11px] text-fg-secondary" title={manifest.sha256}>
                  SHA-256: {manifest.sha256}
                </span>
                <button type="button" onClick={copyChecksum} className="shrink-0 rounded p-1 text-fg-muted hover:text-fg-primary">
                  <Copy className="h-3.5 w-3.5" aria-hidden="true" />
                </button>
              </div>
              <p className="text-[10px] text-fg-muted">
                This checksum lets you verify the bundle was not altered after export — a chain-of-custody record.
              </p>
            </div>
          ) : null}
        </Modal>
      )}
    </>
  );
}
