import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';
import { formatLocalWithZone } from '@/lib/utils/time';

interface CameraSeries {
  cameraId: string;
  name: string;
  zoneId: string | null;
  uptimePct: number | null;
  peakHeadcount: number;
  avgHeadcount: number;
  series: Array<{ ts: string; headcount: number; densityRisk: number }>;
}

// Mirrors the 0.55/0.8 cutoffs used elsewhere for live severity (GroupDetailPanel,
// useClusteredCameras, CameraDetailPanel) — reports show the same breach points an operator
// would have seen live, not a separately-configurable threshold.
const WARNING_AT = 0.55;
const CRITICAL_AT = 0.8;

interface AlertLogEntry {
  cameraId: string;
  severity: string;
  raisedAt: string;
  observedValue: number;
}

export interface ReportPdfData {
  reportId: string;
  generatedBy: string;
  generatedAt: string;
  request: { from: string; to: string };
  cameras: CameraSeries[];
  alertLog: AlertLogEntry[];
}

function drawSparklinePng(
  series: Array<{ headcount: number; densityRisk: number }>,
  width: number,
  height: number,
): Uint8Array | null {
  if (typeof document === 'undefined' || series.length < 2) return null;
  const canvas = document.createElement('canvas');
  canvas.width = width;
  canvas.height = height;
  const ctx = canvas.getContext('2d');
  if (!ctx) return null;
  ctx.fillStyle = '#ffffff';
  ctx.fillRect(0, 0, width, height);
  const values = series.map((s) => s.headcount);
  const max = Math.max(...values, 1);
  const min = Math.min(...values, 0);
  const xAt = (i: number): number => (i / (values.length - 1)) * (width - 4) + 2;
  const yAt = (v: number): number => height - 2 - ((v - min) / Math.max(1, max - min)) * (height - 4);

  ctx.strokeStyle = '#0284c7';
  ctx.lineWidth = 1.5;
  ctx.beginPath();
  values.forEach((v, i) => {
    const x = xAt(i);
    const y = yAt(v);
    if (i === 0) ctx.moveTo(x, y);
    else ctx.lineTo(x, y);
  });
  ctx.stroke();

  // Threshold-breach markers — a dot over every sample where density risk crossed WARNING/
  // CRITICAL, so a reviewer can see breach points on the same timeline as the headcount trend
  // without needing a second chart or axis.
  series.forEach((s, i) => {
    if (s.densityRisk >= CRITICAL_AT) {
      ctx.fillStyle = '#dc2626';
    } else if (s.densityRisk >= WARNING_AT) {
      ctx.fillStyle = '#d97706';
    } else {
      return;
    }
    ctx.beginPath();
    ctx.arc(xAt(i), yAt(values[i]!), 2.25, 0, Math.PI * 2);
    ctx.fill();
  });

  const dataUrl = canvas.toDataURL('image/png');
  const base64 = dataUrl.split(',')[1]!;
  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return bytes;
}

async function sha256Hex(bytes: Uint8Array): Promise<string> {
  const digest = await crypto.subtle.digest('SHA-256', bytes);
  return Array.from(new Uint8Array(digest))
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('');
}

export async function buildReportPdf(
  data: ReportPdfData,
  meta: { departmentName: string; generatedByDisplayName: string },
): Promise<{ bytes: Uint8Array; sha256: string }> {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const pageSize: [number, number] = [612, 792];
  const margin = 48;

  function addPage(): { page: import('pdf-lib').PDFPage; y: number } {
    const page = doc.addPage(pageSize);
    let y = pageSize[1] - margin;
    page.drawText(meta.departmentName, { x: margin, y, size: 14, font: bold, color: rgb(0.1, 0.1, 0.1) });
    y -= 16;
    page.drawText(`Crowd Density Report — ${data.reportId}`, { x: margin, y, size: 10, font, color: rgb(0.3, 0.3, 0.3) });
    y -= 14;
    page.drawText(
      `Generated by ${meta.generatedByDisplayName} at ${formatLocalWithZone(data.generatedAt)} · Range: ${formatLocalWithZone(data.request.from)} – ${formatLocalWithZone(data.request.to)}`,
      { x: margin, y, size: 8, font, color: rgb(0.4, 0.4, 0.4) },
    );
    y -= 24;
    page.drawLine({ start: { x: margin, y }, end: { x: pageSize[0] - margin, y }, thickness: 0.5, color: rgb(0.8, 0.8, 0.8) });
    y -= 20;
    // Footer watermark
    page.drawText(`SYSTEM-GENERATED — Report ID ${data.reportId} — Page ${doc.getPageCount()}`, {
      x: margin,
      y: 24,
      size: 7,
      font,
      color: rgb(0.6, 0.6, 0.6),
    });
    return { page, y };
  }

  let { page, y } = addPage();

  page.drawText('Camera Summary', { x: margin, y, size: 12, font: bold });
  y -= 18;

  for (const cam of data.cameras) {
    if (y < 140) {
      ({ page, y } = addPage());
    }
    page.drawText(`${cam.name} (${cam.cameraId})`, { x: margin, y, size: 10, font: bold });
    y -= 13;
    page.drawText(
      `Peak: ${cam.peakHeadcount}  ·  Avg: ${cam.avgHeadcount.toFixed(1)}  ·  Uptime: ${cam.uptimePct !== null ? cam.uptimePct.toFixed(1) + '%' : 'n/a'}`,
      { x: margin, y, size: 8, font, color: rgb(0.35, 0.35, 0.35) },
    );
    y -= 12;

    const png = drawSparklinePng(cam.series, 300, 60);
    if (png) {
      const img = await doc.embedPng(png);
      page.drawImage(img, { x: margin, y: y - 60, width: 300, height: 60 });
      y -= 72;
    } else {
      y -= 8;
    }
  }

  if (data.alertLog.length > 0) {
    if (y < 200) ({ page, y } = addPage());
    page.drawText('Alert Log', { x: margin, y, size: 12, font: bold });
    y -= 16;
    for (const a of data.alertLog.slice(0, 40)) {
      if (y < 60) ({ page, y } = addPage());
      page.drawText(`${formatLocalWithZone(a.raisedAt)} — ${a.cameraId} — ${a.severity} (${(a.observedValue * 100).toFixed(0)}%)`, {
        x: margin,
        y,
        size: 8,
        font,
        color: rgb(0.25, 0.25, 0.25),
      });
      y -= 12;
    }
  }

  const bytes = await doc.save();
  const sha256 = await sha256Hex(bytes);
  return { bytes, sha256 };
}

export function downloadBytes(bytes: Uint8Array, filename: string, mime: string): void {
  const blob = new Blob([bytes], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

export function buildReportCsv(data: ReportPdfData): string {
  const rows = [['cameraId', 'name', 'ts', 'headcount', 'densityRisk']];
  for (const cam of data.cameras) {
    for (const point of cam.series) {
      rows.push([cam.cameraId, cam.name, point.ts, String(point.headcount), String(point.densityRisk)]);
    }
  }
  return rows.map((r) => r.map((v) => `"${v.replace(/"/g, '""')}"`).join(',')).join('\n');
}
