import { useState } from 'react';
import { Download, FileText, Loader2 } from 'lucide-react';
import { useReportJob, useReportData } from './api';
import { buildReportPdf, buildReportCsv, downloadBytes, type ReportPdfData } from './pdfExport';
import { useSessionStore } from '@/lib/state/sessionStore';
import { formatLocalWithZone } from '@/lib/utils/time';
import { auditQueue } from '@/lib/audit/auditQueue';

interface Props {
  jobId: string;
}

const DEPARTMENT_NAME = import.meta.env.VITE_DEPARTMENT_NAME || 'Police Department';

export function ReportViewer({ jobId }: Props): React.JSX.Element {
  const { data: job } = useReportJob(jobId);
  const { data } = useReportData<ReportPdfData>(job);
  const user = useSessionStore((s) => s.user);
  const [exporting, setExporting] = useState<'pdf' | 'csv' | null>(null);

  if (!job) return <p className="p-4 text-xs text-fg-muted">Loading…</p>;
  if (job.status !== 'DONE' || !data) return <p className="p-4 text-xs text-fg-muted">Report is still processing…</p>;

  async function handleExportPdf(): Promise<void> {
    setExporting('pdf');
    try {
      const { bytes, sha256 } = await buildReportPdf(data!, { departmentName: DEPARTMENT_NAME, generatedByDisplayName: user?.displayName ?? 'Unknown' });
      downloadBytes(bytes, `${data!.reportId}.pdf`, 'application/pdf');
      auditQueue.enqueue('report.export_pdf', null, { reportId: data!.reportId, sha256 });
    } finally {
      setExporting(null);
    }
  }

  function handleExportCsv(): void {
    setExporting('csv');
    const csv = buildReportCsv(data!);
    downloadBytes(new TextEncoder().encode(csv), `${data!.reportId}.csv`, 'text/csv');
    auditQueue.enqueue('report.export_csv', null, { reportId: data!.reportId });
    setExporting(null);
  }

  return (
    <div className="space-y-4 p-4">
      <div className="flex items-center justify-between">
        <div>
          <h3 className="text-sm font-semibold text-fg-primary">{data.reportId}</h3>
          <p className="text-[11px] text-fg-muted">
            {formatLocalWithZone(data.request.from)} – {formatLocalWithZone(data.request.to)} · generated by {data.generatedBy}
          </p>
        </div>
        <div className="flex gap-2">
          <button
            type="button"
            onClick={() => void handleExportPdf()}
            disabled={exporting !== null}
            className="flex items-center gap-1.5 rounded-md border border-border px-2.5 py-1 text-xs text-fg-secondary hover:bg-bg-raised disabled:opacity-50"
          >
            {exporting === 'pdf' ? <Loader2 className="h-3.5 w-3.5 animate-spin" aria-hidden="true" /> : <FileText className="h-3.5 w-3.5" aria-hidden="true" />}
            PDF
          </button>
          <button
            type="button"
            onClick={handleExportCsv}
            disabled={exporting !== null}
            className="flex items-center gap-1.5 rounded-md border border-border px-2.5 py-1 text-xs text-fg-secondary hover:bg-bg-raised disabled:opacity-50"
          >
            <Download className="h-3.5 w-3.5" aria-hidden="true" />
            CSV
          </button>
        </div>
      </div>

      <table className="w-full text-left text-xs">
        <thead className="text-[10px] uppercase text-fg-muted">
          <tr>
            <th className="py-1">Camera</th>
            <th className="py-1">Peak</th>
            <th className="py-1">Avg</th>
            <th className="py-1">Uptime</th>
          </tr>
        </thead>
        <tbody>
          {data.cameras.map((c) => (
            <tr key={c.cameraId} className="border-t border-border">
              <td className="py-1.5">{c.name}</td>
              <td className="py-1.5 font-mono">{c.peakHeadcount}</td>
              <td className="py-1.5 font-mono">{c.avgHeadcount.toFixed(1)}</td>
              <td className="py-1.5 font-mono">{c.uptimePct !== null ? `${c.uptimePct.toFixed(1)}%` : 'n/a'}</td>
            </tr>
          ))}
        </tbody>
      </table>

      {data.alertLog.length > 0 && (
        <div>
          <h4 className="mb-1 text-[11px] font-semibold uppercase tracking-wide text-fg-muted">Alert log ({data.alertLog.length})</h4>
          <ul className="max-h-40 space-y-1 overflow-y-auto text-[11px] text-fg-secondary">
            {data.alertLog.slice(0, 30).map((a, i) => (
              <li key={i}>
                {formatLocalWithZone(a.raisedAt)} — {a.cameraId} — {a.severity}
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
}
